from scipy.constants import g


# WINDOW CONSTANTS
WIDTH = 1000
HEIGHT = 800
FPS = 100
CAPTION = "ACAS-2D"
FONT_NAME = "freesansbold.ttf"
FONT_SIZE = 14
FONT_RGB = (0, 0, 0)
SKY_RGB = (204, 204, 255)
GREEN_RGB = (0, 255, 0)
RED_RGB = (255, 0, 0)

# RANDOM SEED
RANDOM_SEED = 42

# AIRCRAFT CONSTANTS
MIN_TRAFFIC = 0
MAX_TRAFFIC = 0
AIRCRAFT_SIZE = 24  # images used are 24x24 pixels
COLLISION_RADIUS = 48
GOAL_RADIUS = 96

# KINEMATICS CONSTANTS
AIRSPEED = 120
AIRSPEED_FACTOR_MIN = 1
AIRSPEED_FACTOR_MAX = 1
ACC_LAT_LIMIT = 2400 * g
# MIN_BOUNCE_ANGLE = 120
# MAX_BOUNCE_ANGLE = 240
INITIAL_HEADING_LIM = 5

# GAME CONSTANTS
EPISODES = 10
MAX_STEPS = 1000
TOTAL_STEPS = 3*1e4
OUTCOME_NAMES = {1: 'Goal', 2: 'Collision', 3: 'Timeout', 4: 'Runaway'}

# REWARD CONSTANTS
REWARD_GOAL = 1000
REWARD_COLLISION = -2000
# REWARD_TIMEOUT_FACTOR = 1
# REWARD_RUNAWAY_FACTOR = 1

# IMAGE FILES
LOGO = "png/004-compass.png"
PLAYER_IMG = "png/001-plane.png"
TRAFFIC_IMG = "png/002-travelling.png"
GOAL_IMG = "png/003-army.png"
